//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Power
{
    [Serializable]
    public class BreakerCommandRequest : Message
    {
        public const string k_RosMessageName = "power_msgs/BreakerCommand";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Service for enabling/disabling breakers
        // 
        public bool enable;

        public BreakerCommandRequest()
        {
            this.enable = false;
        }

        public BreakerCommandRequest(bool enable)
        {
            this.enable = enable;
        }

        public static BreakerCommandRequest Deserialize(MessageDeserializer deserializer) => new BreakerCommandRequest(deserializer);

        private BreakerCommandRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.enable);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.enable);
        }

        public override string ToString()
        {
            return "BreakerCommandRequest: " +
            "\nenable: " + enable.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
