//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.GopherRosClearcore
{
    [Serializable]
    public class PositionMsg : Message
    {
        public const string k_RosMessageName = "gopher_ros_clearcore/Position";
        public override string RosMessageName => k_RosMessageName;

        public double position;
        public double velocity;

        public PositionMsg()
        {
            this.position = 0.0;
            this.velocity = 0.0;
        }

        public PositionMsg(double position, double velocity)
        {
            this.position = position;
            this.velocity = velocity;
        }

        public static PositionMsg Deserialize(MessageDeserializer deserializer) => new PositionMsg(deserializer);

        private PositionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.position);
            deserializer.Read(out this.velocity);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.position);
            serializer.Write(this.velocity);
        }

        public override string ToString()
        {
            return "PositionMsg: " +
            "\nposition: " + position.ToString() +
            "\nvelocity: " + velocity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
