//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KortexDriver
{
    [Serializable]
    public class FingerMsg : Message
    {
        public const string k_RosMessageName = "kortex_driver/Finger";
        public override string RosMessageName => k_RosMessageName;

        public uint finger_identifier;
        public float value;

        public FingerMsg()
        {
            this.finger_identifier = 0;
            this.value = 0.0f;
        }

        public FingerMsg(uint finger_identifier, float value)
        {
            this.finger_identifier = finger_identifier;
            this.value = value;
        }

        public static FingerMsg Deserialize(MessageDeserializer deserializer) => new FingerMsg(deserializer);

        private FingerMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.finger_identifier);
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.finger_identifier);
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "FingerMsg: " +
            "\nfinger_identifier: " + finger_identifier.ToString() +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
