//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KortexDriver
{
    [Serializable]
    public class GripperCommandMsg : Message
    {
        public const string k_RosMessageName = "kortex_driver/GripperCommand";
        public override string RosMessageName => k_RosMessageName;

        public uint mode;
        public GripperMsg gripper;
        public uint duration;

        public GripperCommandMsg()
        {
            this.mode = 0;
            this.gripper = new GripperMsg();
            this.duration = 0;
        }

        public GripperCommandMsg(uint mode, GripperMsg gripper, uint duration)
        {
            this.mode = mode;
            this.gripper = gripper;
            this.duration = duration;
        }

        public static GripperCommandMsg Deserialize(MessageDeserializer deserializer) => new GripperCommandMsg(deserializer);

        private GripperCommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mode);
            this.gripper = GripperMsg.Deserialize(deserializer);
            deserializer.Read(out this.duration);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mode);
            serializer.Write(this.gripper);
            serializer.Write(this.duration);
        }

        public override string ToString()
        {
            return "GripperCommandMsg: " +
            "\nmode: " + mode.ToString() +
            "\ngripper: " + gripper.ToString() +
            "\nduration: " + duration.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
