//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KortexDriver
{
    [Serializable]
    public class GripperMsg : Message
    {
        public const string k_RosMessageName = "kortex_driver/Gripper";
        public override string RosMessageName => k_RosMessageName;

        public FingerMsg[] finger;

        public GripperMsg()
        {
            this.finger = new FingerMsg[0];
        }

        public GripperMsg(FingerMsg[] finger)
        {
            this.finger = finger;
        }

        public static GripperMsg Deserialize(MessageDeserializer deserializer) => new GripperMsg(deserializer);

        private GripperMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.finger, FingerMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.finger);
            serializer.Write(this.finger);
        }

        public override string ToString()
        {
            return "GripperMsg: " +
            "\nfinger: " + System.String.Join(", ", finger.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
