//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KortexDriver
{
    [Serializable]
    public class TwistCommandMsg : Message
    {
        public const string k_RosMessageName = "kortex_driver/TwistCommand";
        public override string RosMessageName => k_RosMessageName;

        public uint reference_frame;
        public TwistMsg twist;
        public uint duration;

        public TwistCommandMsg()
        {
            this.reference_frame = 0;
            this.twist = new TwistMsg();
            this.duration = 0;
        }

        public TwistCommandMsg(uint reference_frame, TwistMsg twist, uint duration)
        {
            this.reference_frame = reference_frame;
            this.twist = twist;
            this.duration = duration;
        }

        public static TwistCommandMsg Deserialize(MessageDeserializer deserializer) => new TwistCommandMsg(deserializer);

        private TwistCommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.reference_frame);
            this.twist = TwistMsg.Deserialize(deserializer);
            deserializer.Read(out this.duration);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.reference_frame);
            serializer.Write(this.twist);
            serializer.Write(this.duration);
        }

        public override string ToString()
        {
            return "TwistCommandMsg: " +
            "\nreference_frame: " + reference_frame.ToString() +
            "\ntwist: " + twist.ToString() +
            "\nduration: " + duration.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
