//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.GopherNavigation
{
    [Serializable]
    public class TFListenerServiceRequest : Message
    {
        public const string k_RosMessageName = "gopher_navigation/TFListenerService";
        public override string RosMessageName => k_RosMessageName;

        public string parent_frame;
        public string child_frame;

        public TFListenerServiceRequest()
        {
            this.parent_frame = "";
            this.child_frame = "";
        }

        public TFListenerServiceRequest(string parent_frame, string child_frame)
        {
            this.parent_frame = parent_frame;
            this.child_frame = child_frame;
        }

        public static TFListenerServiceRequest Deserialize(MessageDeserializer deserializer) => new TFListenerServiceRequest(deserializer);

        private TFListenerServiceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.parent_frame);
            deserializer.Read(out this.child_frame);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.parent_frame);
            serializer.Write(this.child_frame);
        }

        public override string ToString()
        {
            return "TFListenerServiceRequest: " +
            "\nparent_frame: " + parent_frame.ToString() +
            "\nchild_frame: " + child_frame.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
