//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.GopherNavigation
{
    [Serializable]
    public class TFListenerServiceResponse : Message
    {
        public const string k_RosMessageName = "gopher_navigation/TFListenerService";
        public override string RosMessageName => k_RosMessageName;

        public bool isValidTransform;

        public TFListenerServiceResponse()
        {
            this.isValidTransform = false;
        }

        public TFListenerServiceResponse(bool isValidTransform)
        {
            this.isValidTransform = isValidTransform;
        }

        public static TFListenerServiceResponse Deserialize(MessageDeserializer deserializer) => new TFListenerServiceResponse(deserializer);

        private TFListenerServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.isValidTransform);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.isValidTransform);
        }

        public override string ToString()
        {
            return "TFListenerServiceResponse: " +
            "\nisValidTransform: " + isValidTransform.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
