//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KortexDriver
{
    [Serializable]
    public class SendGripperCommandResponse : Message
    {
        public const string k_RosMessageName = "kortex_driver/SendGripperCommand";
        public override string RosMessageName => k_RosMessageName;

        public EmptyMsg output;

        public SendGripperCommandResponse()
        {
            this.output = new EmptyMsg();
        }

        public SendGripperCommandResponse(EmptyMsg output)
        {
            this.output = output;
        }

        public static SendGripperCommandResponse Deserialize(MessageDeserializer deserializer) => new SendGripperCommandResponse(deserializer);

        private SendGripperCommandResponse(MessageDeserializer deserializer)
        {
            this.output = EmptyMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.output);
        }

        public override string ToString()
        {
            return "SendGripperCommandResponse: " +
            "\noutput: " + output.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
