//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.GopherMoveit
{
    [Serializable]
    public class PlanTrajectoryRequest : Message
    {
        public const string k_RosMessageName = "gopher_moveit/PlanTrajectory";
        public override string RosMessageName => k_RosMessageName;

        public float[] joints_input;
        public Geometry.PoseMsg target_pose;

        public PlanTrajectoryRequest()
        {
            this.joints_input = new float[0];
            this.target_pose = new Geometry.PoseMsg();
        }

        public PlanTrajectoryRequest(float[] joints_input, Geometry.PoseMsg target_pose)
        {
            this.joints_input = joints_input;
            this.target_pose = target_pose;
        }

        public static PlanTrajectoryRequest Deserialize(MessageDeserializer deserializer) => new PlanTrajectoryRequest(deserializer);

        private PlanTrajectoryRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joints_input, sizeof(float), deserializer.ReadLength());
            this.target_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.joints_input);
            serializer.Write(this.joints_input);
            serializer.Write(this.target_pose);
        }

        public override string ToString()
        {
            return "PlanTrajectoryRequest: " +
            "\njoints_input: " + System.String.Join(", ", joints_input.ToList()) +
            "\ntarget_pose: " + target_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
