//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class AllowedCollisionEntryMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/AllowedCollisionEntry";
        public override string RosMessageName => k_RosMessageName;

        //  whether or not collision checking is enabled
        public bool[] enabled;

        public AllowedCollisionEntryMsg()
        {
            this.enabled = new bool[0];
        }

        public AllowedCollisionEntryMsg(bool[] enabled)
        {
            this.enabled = enabled;
        }

        public static AllowedCollisionEntryMsg Deserialize(MessageDeserializer deserializer) => new AllowedCollisionEntryMsg(deserializer);

        private AllowedCollisionEntryMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.enabled, sizeof(bool), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.enabled);
            serializer.Write(this.enabled);
        }

        public override string ToString()
        {
            return "AllowedCollisionEntryMsg: " +
            "\nenabled: " + System.String.Join(", ", enabled.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
