//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class BoundingVolumeMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/BoundingVolume";
        public override string RosMessageName => k_RosMessageName;

        //  Define a volume in 3D
        //  A set of solid geometric primitives that make up the volume to define (as a union)
        public Shape.SolidPrimitiveMsg[] primitives;
        //  The poses at which the primitives are located
        public Geometry.PoseMsg[] primitive_poses;
        //  In addition to primitives, meshes can be specified to add to the bounding volume (again, as union)
        public Shape.MeshMsg[] meshes;
        //  The poses at which the meshes are located
        public Geometry.PoseMsg[] mesh_poses;

        public BoundingVolumeMsg()
        {
            this.primitives = new Shape.SolidPrimitiveMsg[0];
            this.primitive_poses = new Geometry.PoseMsg[0];
            this.meshes = new Shape.MeshMsg[0];
            this.mesh_poses = new Geometry.PoseMsg[0];
        }

        public BoundingVolumeMsg(Shape.SolidPrimitiveMsg[] primitives, Geometry.PoseMsg[] primitive_poses, Shape.MeshMsg[] meshes, Geometry.PoseMsg[] mesh_poses)
        {
            this.primitives = primitives;
            this.primitive_poses = primitive_poses;
            this.meshes = meshes;
            this.mesh_poses = mesh_poses;
        }

        public static BoundingVolumeMsg Deserialize(MessageDeserializer deserializer) => new BoundingVolumeMsg(deserializer);

        private BoundingVolumeMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.primitives, Shape.SolidPrimitiveMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.primitive_poses, Geometry.PoseMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.meshes, Shape.MeshMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.mesh_poses, Geometry.PoseMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.primitives);
            serializer.Write(this.primitives);
            serializer.WriteLength(this.primitive_poses);
            serializer.Write(this.primitive_poses);
            serializer.WriteLength(this.meshes);
            serializer.Write(this.meshes);
            serializer.WriteLength(this.mesh_poses);
            serializer.Write(this.mesh_poses);
        }

        public override string ToString()
        {
            return "BoundingVolumeMsg: " +
            "\nprimitives: " + System.String.Join(", ", primitives.ToList()) +
            "\nprimitive_poses: " + System.String.Join(", ", primitive_poses.ToList()) +
            "\nmeshes: " + System.String.Join(", ", meshes.ToList()) +
            "\nmesh_poses: " + System.String.Join(", ", mesh_poses.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
