//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class CartesianPointMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/CartesianPoint";
        public override string RosMessageName => k_RosMessageName;

        //  This message defines a point in a cartesian trajectory
        public Geometry.PoseMsg pose;
        public Geometry.TwistMsg velocity;
        public Geometry.AccelMsg acceleration;

        public CartesianPointMsg()
        {
            this.pose = new Geometry.PoseMsg();
            this.velocity = new Geometry.TwistMsg();
            this.acceleration = new Geometry.AccelMsg();
        }

        public CartesianPointMsg(Geometry.PoseMsg pose, Geometry.TwistMsg velocity, Geometry.AccelMsg acceleration)
        {
            this.pose = pose;
            this.velocity = velocity;
            this.acceleration = acceleration;
        }

        public static CartesianPointMsg Deserialize(MessageDeserializer deserializer) => new CartesianPointMsg(deserializer);

        private CartesianPointMsg(MessageDeserializer deserializer)
        {
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.velocity = Geometry.TwistMsg.Deserialize(deserializer);
            this.acceleration = Geometry.AccelMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose);
            serializer.Write(this.velocity);
            serializer.Write(this.acceleration);
        }

        public override string ToString()
        {
            return "CartesianPointMsg: " +
            "\npose: " + pose.ToString() +
            "\nvelocity: " + velocity.ToString() +
            "\nacceleration: " + acceleration.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
