//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class CartesianTrajectoryMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/CartesianTrajectory";
        public override string RosMessageName => k_RosMessageName;

        //  This message describes the trajectory of a tracked frame in task-space
        public HeaderMsg header;
        //  The name of the Cartesian frame being tracked with respect to the base frame provided in header.frame_id
        public string tracked_frame;
        public CartesianTrajectoryPointMsg[] points;

        public CartesianTrajectoryMsg()
        {
            this.header = new HeaderMsg();
            this.tracked_frame = "";
            this.points = new CartesianTrajectoryPointMsg[0];
        }

        public CartesianTrajectoryMsg(HeaderMsg header, string tracked_frame, CartesianTrajectoryPointMsg[] points)
        {
            this.header = header;
            this.tracked_frame = tracked_frame;
            this.points = points;
        }

        public static CartesianTrajectoryMsg Deserialize(MessageDeserializer deserializer) => new CartesianTrajectoryMsg(deserializer);

        private CartesianTrajectoryMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.tracked_frame);
            deserializer.Read(out this.points, CartesianTrajectoryPointMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.tracked_frame);
            serializer.WriteLength(this.points);
            serializer.Write(this.points);
        }

        public override string ToString()
        {
            return "CartesianTrajectoryMsg: " +
            "\nheader: " + header.ToString() +
            "\ntracked_frame: " + tracked_frame.ToString() +
            "\npoints: " + System.String.Join(", ", points.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
