//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class ConstraintsMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/Constraints";
        public override string RosMessageName => k_RosMessageName;

        //  This message contains a list of motion planning constraints.
        //  All constraints must be satisfied for a goal to be considered valid
        public string name;
        public JointConstraintMsg[] joint_constraints;
        public PositionConstraintMsg[] position_constraints;
        public OrientationConstraintMsg[] orientation_constraints;
        public VisibilityConstraintMsg[] visibility_constraints;

        public ConstraintsMsg()
        {
            this.name = "";
            this.joint_constraints = new JointConstraintMsg[0];
            this.position_constraints = new PositionConstraintMsg[0];
            this.orientation_constraints = new OrientationConstraintMsg[0];
            this.visibility_constraints = new VisibilityConstraintMsg[0];
        }

        public ConstraintsMsg(string name, JointConstraintMsg[] joint_constraints, PositionConstraintMsg[] position_constraints, OrientationConstraintMsg[] orientation_constraints, VisibilityConstraintMsg[] visibility_constraints)
        {
            this.name = name;
            this.joint_constraints = joint_constraints;
            this.position_constraints = position_constraints;
            this.orientation_constraints = orientation_constraints;
            this.visibility_constraints = visibility_constraints;
        }

        public static ConstraintsMsg Deserialize(MessageDeserializer deserializer) => new ConstraintsMsg(deserializer);

        private ConstraintsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.joint_constraints, JointConstraintMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.position_constraints, PositionConstraintMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.orientation_constraints, OrientationConstraintMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.visibility_constraints, VisibilityConstraintMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.WriteLength(this.joint_constraints);
            serializer.Write(this.joint_constraints);
            serializer.WriteLength(this.position_constraints);
            serializer.Write(this.position_constraints);
            serializer.WriteLength(this.orientation_constraints);
            serializer.Write(this.orientation_constraints);
            serializer.WriteLength(this.visibility_constraints);
            serializer.Write(this.visibility_constraints);
        }

        public override string ToString()
        {
            return "ConstraintsMsg: " +
            "\nname: " + name.ToString() +
            "\njoint_constraints: " + System.String.Join(", ", joint_constraints.ToList()) +
            "\nposition_constraints: " + System.String.Join(", ", position_constraints.ToList()) +
            "\norientation_constraints: " + System.String.Join(", ", orientation_constraints.ToList()) +
            "\nvisibility_constraints: " + System.String.Join(", ", visibility_constraints.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
