//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class ConstraintEvalResultMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/ConstraintEvalResult";
        public override string RosMessageName => k_RosMessageName;

        //  This message contains result from constraint evaluation
        //  result specifies the result of constraint evaluation
        //  (true indicates state satisfies constraint, false indicates state violates constraint)
        //  if false, distance specifies a measure of the distance of the state from the constraint
        //  if true, distance is set to zero
        public bool result;
        public double distance;

        public ConstraintEvalResultMsg()
        {
            this.result = false;
            this.distance = 0.0;
        }

        public ConstraintEvalResultMsg(bool result, double distance)
        {
            this.result = result;
            this.distance = distance;
        }

        public static ConstraintEvalResultMsg Deserialize(MessageDeserializer deserializer) => new ConstraintEvalResultMsg(deserializer);

        private ConstraintEvalResultMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.result);
            deserializer.Read(out this.distance);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
            serializer.Write(this.distance);
        }

        public override string ToString()
        {
            return "ConstraintEvalResultMsg: " +
            "\nresult: " + result.ToString() +
            "\ndistance: " + distance.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
