//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class ContactInformationMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/ContactInformation";
        public override string RosMessageName => k_RosMessageName;

        //  Standard ROS header contains information
        //  about the frame in which this
        //  contact is specified
        public HeaderMsg header;
        //  Position of the contact point
        public Geometry.PointMsg position;
        //  Normal corresponding to the contact point
        public Geometry.Vector3Msg normal;
        //  Depth of contact point
        public double depth;
        //  Name of the first body that is in contact
        //  This could be a link or a namespace that represents a body
        public string contact_body_1;
        public uint body_type_1;
        //  Name of the second body that is in contact
        //  This could be a link or a namespace that represents a body
        public string contact_body_2;
        public uint body_type_2;
        public const uint ROBOT_LINK = 0;
        public const uint WORLD_OBJECT = 1;
        public const uint ROBOT_ATTACHED = 2;

        public ContactInformationMsg()
        {
            this.header = new HeaderMsg();
            this.position = new Geometry.PointMsg();
            this.normal = new Geometry.Vector3Msg();
            this.depth = 0.0;
            this.contact_body_1 = "";
            this.body_type_1 = 0;
            this.contact_body_2 = "";
            this.body_type_2 = 0;
        }

        public ContactInformationMsg(HeaderMsg header, Geometry.PointMsg position, Geometry.Vector3Msg normal, double depth, string contact_body_1, uint body_type_1, string contact_body_2, uint body_type_2)
        {
            this.header = header;
            this.position = position;
            this.normal = normal;
            this.depth = depth;
            this.contact_body_1 = contact_body_1;
            this.body_type_1 = body_type_1;
            this.contact_body_2 = contact_body_2;
            this.body_type_2 = body_type_2;
        }

        public static ContactInformationMsg Deserialize(MessageDeserializer deserializer) => new ContactInformationMsg(deserializer);

        private ContactInformationMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.position = Geometry.PointMsg.Deserialize(deserializer);
            this.normal = Geometry.Vector3Msg.Deserialize(deserializer);
            deserializer.Read(out this.depth);
            deserializer.Read(out this.contact_body_1);
            deserializer.Read(out this.body_type_1);
            deserializer.Read(out this.contact_body_2);
            deserializer.Read(out this.body_type_2);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.position);
            serializer.Write(this.normal);
            serializer.Write(this.depth);
            serializer.Write(this.contact_body_1);
            serializer.Write(this.body_type_1);
            serializer.Write(this.contact_body_2);
            serializer.Write(this.body_type_2);
        }

        public override string ToString()
        {
            return "ContactInformationMsg: " +
            "\nheader: " + header.ToString() +
            "\nposition: " + position.ToString() +
            "\nnormal: " + normal.ToString() +
            "\ndepth: " + depth.ToString() +
            "\ncontact_body_1: " + contact_body_1.ToString() +
            "\nbody_type_1: " + body_type_1.ToString() +
            "\ncontact_body_2: " + contact_body_2.ToString() +
            "\nbody_type_2: " + body_type_2.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
