//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class CostSourceMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/CostSource";
        public override string RosMessageName => k_RosMessageName;

        //  The density of the cost source
        public double cost_density;
        //  The volume of the cost source is represented as an
        //  axis-aligned bounding box (AABB)
        //  The AABB is specified by two of its opposite corners
        public Geometry.Vector3Msg aabb_min;
        public Geometry.Vector3Msg aabb_max;

        public CostSourceMsg()
        {
            this.cost_density = 0.0;
            this.aabb_min = new Geometry.Vector3Msg();
            this.aabb_max = new Geometry.Vector3Msg();
        }

        public CostSourceMsg(double cost_density, Geometry.Vector3Msg aabb_min, Geometry.Vector3Msg aabb_max)
        {
            this.cost_density = cost_density;
            this.aabb_min = aabb_min;
            this.aabb_max = aabb_max;
        }

        public static CostSourceMsg Deserialize(MessageDeserializer deserializer) => new CostSourceMsg(deserializer);

        private CostSourceMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cost_density);
            this.aabb_min = Geometry.Vector3Msg.Deserialize(deserializer);
            this.aabb_max = Geometry.Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cost_density);
            serializer.Write(this.aabb_min);
            serializer.Write(this.aabb_max);
        }

        public override string ToString()
        {
            return "CostSourceMsg: " +
            "\ncost_density: " + cost_density.ToString() +
            "\naabb_min: " + aabb_min.ToString() +
            "\naabb_max: " + aabb_max.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
