//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class KinematicSolverInfoMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/KinematicSolverInfo";
        public override string RosMessageName => k_RosMessageName;

        //  A list of joints in the kinematic tree
        public string[] joint_names;
        //  A list of joint limits corresponding to the joint names
        public JointLimitsMsg[] limits;
        //  A list of links that the kinematics node provides solutions for
        public string[] link_names;

        public KinematicSolverInfoMsg()
        {
            this.joint_names = new string[0];
            this.limits = new JointLimitsMsg[0];
            this.link_names = new string[0];
        }

        public KinematicSolverInfoMsg(string[] joint_names, JointLimitsMsg[] limits, string[] link_names)
        {
            this.joint_names = joint_names;
            this.limits = limits;
            this.link_names = link_names;
        }

        public static KinematicSolverInfoMsg Deserialize(MessageDeserializer deserializer) => new KinematicSolverInfoMsg(deserializer);

        private KinematicSolverInfoMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joint_names, deserializer.ReadLength());
            deserializer.Read(out this.limits, JointLimitsMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.link_names, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.joint_names);
            serializer.Write(this.joint_names);
            serializer.WriteLength(this.limits);
            serializer.Write(this.limits);
            serializer.WriteLength(this.link_names);
            serializer.Write(this.link_names);
        }

        public override string ToString()
        {
            return "KinematicSolverInfoMsg: " +
            "\njoint_names: " + System.String.Join(", ", joint_names.ToList()) +
            "\nlimits: " + System.String.Join(", ", limits.ToList()) +
            "\nlink_names: " + System.String.Join(", ", link_names.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
