//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class LinkPaddingMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/LinkPadding";
        public override string RosMessageName => k_RosMessageName;

        // name for the link
        public string link_name;
        //  padding to apply to the link
        public double padding;

        public LinkPaddingMsg()
        {
            this.link_name = "";
            this.padding = 0.0;
        }

        public LinkPaddingMsg(string link_name, double padding)
        {
            this.link_name = link_name;
            this.padding = padding;
        }

        public static LinkPaddingMsg Deserialize(MessageDeserializer deserializer) => new LinkPaddingMsg(deserializer);

        private LinkPaddingMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.link_name);
            deserializer.Read(out this.padding);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.link_name);
            serializer.Write(this.padding);
        }

        public override string ToString()
        {
            return "LinkPaddingMsg: " +
            "\nlink_name: " + link_name.ToString() +
            "\npadding: " + padding.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
