//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class LinkScaleMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/LinkScale";
        public override string RosMessageName => k_RosMessageName;

        // name for the link
        public string link_name;
        //  scaling to apply to the link
        public double scale;

        public LinkScaleMsg()
        {
            this.link_name = "";
            this.scale = 0.0;
        }

        public LinkScaleMsg(string link_name, double scale)
        {
            this.link_name = link_name;
            this.scale = scale;
        }

        public static LinkScaleMsg Deserialize(MessageDeserializer deserializer) => new LinkScaleMsg(deserializer);

        private LinkScaleMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.link_name);
            deserializer.Read(out this.scale);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.link_name);
            serializer.Write(this.scale);
        }

        public override string ToString()
        {
            return "LinkScaleMsg: " +
            "\nlink_name: " + link_name.ToString() +
            "\nscale: " + scale.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
