//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class MotionPlanResponseMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/MotionPlanResponse";
        public override string RosMessageName => k_RosMessageName;

        //  The representation of a solution to a planning problem
        //  The corresponding robot state
        public RobotStateMsg trajectory_start;
        //  The group used for planning (usually the same as in the request)
        public string group_name;
        //  A solution trajectory, if found
        public RobotTrajectoryMsg trajectory;
        //  Planning time (seconds)
        public double planning_time;
        //  Error code - encodes the overall reason for failure
        public MoveItErrorCodesMsg error_code;

        public MotionPlanResponseMsg()
        {
            this.trajectory_start = new RobotStateMsg();
            this.group_name = "";
            this.trajectory = new RobotTrajectoryMsg();
            this.planning_time = 0.0;
            this.error_code = new MoveItErrorCodesMsg();
        }

        public MotionPlanResponseMsg(RobotStateMsg trajectory_start, string group_name, RobotTrajectoryMsg trajectory, double planning_time, MoveItErrorCodesMsg error_code)
        {
            this.trajectory_start = trajectory_start;
            this.group_name = group_name;
            this.trajectory = trajectory;
            this.planning_time = planning_time;
            this.error_code = error_code;
        }

        public static MotionPlanResponseMsg Deserialize(MessageDeserializer deserializer) => new MotionPlanResponseMsg(deserializer);

        private MotionPlanResponseMsg(MessageDeserializer deserializer)
        {
            this.trajectory_start = RobotStateMsg.Deserialize(deserializer);
            deserializer.Read(out this.group_name);
            this.trajectory = RobotTrajectoryMsg.Deserialize(deserializer);
            deserializer.Read(out this.planning_time);
            this.error_code = MoveItErrorCodesMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trajectory_start);
            serializer.Write(this.group_name);
            serializer.Write(this.trajectory);
            serializer.Write(this.planning_time);
            serializer.Write(this.error_code);
        }

        public override string ToString()
        {
            return "MotionPlanResponseMsg: " +
            "\ntrajectory_start: " + trajectory_start.ToString() +
            "\ngroup_name: " + group_name.ToString() +
            "\ntrajectory: " + trajectory.ToString() +
            "\nplanning_time: " + planning_time.ToString() +
            "\nerror_code: " + error_code.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
