//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class MotionSequenceRequestMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/MotionSequenceRequest";
        public override string RosMessageName => k_RosMessageName;

        //  List of motion planning request with a blend_radius for each.
        //  In the response of the planner all of these will be executable as one sequence.
        public MotionSequenceItemMsg[] items;

        public MotionSequenceRequestMsg()
        {
            this.items = new MotionSequenceItemMsg[0];
        }

        public MotionSequenceRequestMsg(MotionSequenceItemMsg[] items)
        {
            this.items = items;
        }

        public static MotionSequenceRequestMsg Deserialize(MessageDeserializer deserializer) => new MotionSequenceRequestMsg(deserializer);

        private MotionSequenceRequestMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.items, MotionSequenceItemMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.items);
            serializer.Write(this.items);
        }

        public override string ToString()
        {
            return "MotionSequenceRequestMsg: " +
            "\nitems: " + System.String.Join(", ", items.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
