//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class OrientedBoundingBoxMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/OrientedBoundingBox";
        public override string RosMessageName => k_RosMessageName;

        //  the pose of the box
        public Geometry.PoseMsg pose;
        //  the extents of the box, assuming the center is at the origin
        public Geometry.Point32Msg extents;

        public OrientedBoundingBoxMsg()
        {
            this.pose = new Geometry.PoseMsg();
            this.extents = new Geometry.Point32Msg();
        }

        public OrientedBoundingBoxMsg(Geometry.PoseMsg pose, Geometry.Point32Msg extents)
        {
            this.pose = pose;
            this.extents = extents;
        }

        public static OrientedBoundingBoxMsg Deserialize(MessageDeserializer deserializer) => new OrientedBoundingBoxMsg(deserializer);

        private OrientedBoundingBoxMsg(MessageDeserializer deserializer)
        {
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.extents = Geometry.Point32Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose);
            serializer.Write(this.extents);
        }

        public override string ToString()
        {
            return "OrientedBoundingBoxMsg: " +
            "\npose: " + pose.ToString() +
            "\nextents: " + extents.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
