//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class PlannerParamsMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/PlannerParams";
        public override string RosMessageName => k_RosMessageName;

        //  parameter names (same size as values)
        public string[] keys;
        //  parameter values (same size as keys)
        public string[] values;
        //  parameter description (can be empty)
        public string[] descriptions;

        public PlannerParamsMsg()
        {
            this.keys = new string[0];
            this.values = new string[0];
            this.descriptions = new string[0];
        }

        public PlannerParamsMsg(string[] keys, string[] values, string[] descriptions)
        {
            this.keys = keys;
            this.values = values;
            this.descriptions = descriptions;
        }

        public static PlannerParamsMsg Deserialize(MessageDeserializer deserializer) => new PlannerParamsMsg(deserializer);

        private PlannerParamsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.keys, deserializer.ReadLength());
            deserializer.Read(out this.values, deserializer.ReadLength());
            deserializer.Read(out this.descriptions, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.keys);
            serializer.Write(this.keys);
            serializer.WriteLength(this.values);
            serializer.Write(this.values);
            serializer.WriteLength(this.descriptions);
            serializer.Write(this.descriptions);
        }

        public override string ToString()
        {
            return "PlannerParamsMsg: " +
            "\nkeys: " + System.String.Join(", ", keys.ToList()) +
            "\nvalues: " + System.String.Join(", ", values.ToList()) +
            "\ndescriptions: " + System.String.Join(", ", descriptions.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
