//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class RobotTrajectoryMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/RobotTrajectory";
        public override string RosMessageName => k_RosMessageName;

        public Trajectory.JointTrajectoryMsg joint_trajectory;
        public Trajectory.MultiDOFJointTrajectoryMsg multi_dof_joint_trajectory;

        public RobotTrajectoryMsg()
        {
            this.joint_trajectory = new Trajectory.JointTrajectoryMsg();
            this.multi_dof_joint_trajectory = new Trajectory.MultiDOFJointTrajectoryMsg();
        }

        public RobotTrajectoryMsg(Trajectory.JointTrajectoryMsg joint_trajectory, Trajectory.MultiDOFJointTrajectoryMsg multi_dof_joint_trajectory)
        {
            this.joint_trajectory = joint_trajectory;
            this.multi_dof_joint_trajectory = multi_dof_joint_trajectory;
        }

        public static RobotTrajectoryMsg Deserialize(MessageDeserializer deserializer) => new RobotTrajectoryMsg(deserializer);

        private RobotTrajectoryMsg(MessageDeserializer deserializer)
        {
            this.joint_trajectory = Trajectory.JointTrajectoryMsg.Deserialize(deserializer);
            this.multi_dof_joint_trajectory = Trajectory.MultiDOFJointTrajectoryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joint_trajectory);
            serializer.Write(this.multi_dof_joint_trajectory);
        }

        public override string ToString()
        {
            return "RobotTrajectoryMsg: " +
            "\njoint_trajectory: " + joint_trajectory.ToString() +
            "\nmulti_dof_joint_trajectory: " + multi_dof_joint_trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
