//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class WorkspaceParametersMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/WorkspaceParameters";
        public override string RosMessageName => k_RosMessageName;

        //  This message contains a set of parameters useful in
        //  setting up the volume (a box) in which the robot is allowed to move.
        //  This is useful only when planning for mobile parts of
        //  the robot as well.
        //  Define the frame of reference for the box corners
        public HeaderMsg header;
        //  The minumum corner of the box, with respect to the robot starting pose
        public Geometry.Vector3Msg min_corner;
        //  The maximum corner of the box, with respect to the robot starting pose
        public Geometry.Vector3Msg max_corner;

        public WorkspaceParametersMsg()
        {
            this.header = new HeaderMsg();
            this.min_corner = new Geometry.Vector3Msg();
            this.max_corner = new Geometry.Vector3Msg();
        }

        public WorkspaceParametersMsg(HeaderMsg header, Geometry.Vector3Msg min_corner, Geometry.Vector3Msg max_corner)
        {
            this.header = header;
            this.min_corner = min_corner;
            this.max_corner = max_corner;
        }

        public static WorkspaceParametersMsg Deserialize(MessageDeserializer deserializer) => new WorkspaceParametersMsg(deserializer);

        private WorkspaceParametersMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.min_corner = Geometry.Vector3Msg.Deserialize(deserializer);
            this.max_corner = Geometry.Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.min_corner);
            serializer.Write(this.max_corner);
        }

        public override string ToString()
        {
            return "WorkspaceParametersMsg: " +
            "\nheader: " + header.ToString() +
            "\nmin_corner: " + min_corner.ToString() +
            "\nmax_corner: " + max_corner.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
