//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.GopherMoveItConfig
{
    [Serializable]
    public class PlanTrajectoryRequest : Message
    {
        public const string k_RosMessageName = "gopher_move_it_config/PlanTrajectory";
        public override string RosMessageName => k_RosMessageName;

        public JointsMsg joints;
        public Geometry.PoseMsg target;

        public PlanTrajectoryRequest()
        {
            this.joints = new JointsMsg();
            this.target = new Geometry.PoseMsg();
        }

        public PlanTrajectoryRequest(JointsMsg joints, Geometry.PoseMsg target)
        {
            this.joints = joints;
            this.target = target;
        }

        public static PlanTrajectoryRequest Deserialize(MessageDeserializer deserializer) => new PlanTrajectoryRequest(deserializer);

        private PlanTrajectoryRequest(MessageDeserializer deserializer)
        {
            this.joints = JointsMsg.Deserialize(deserializer);
            this.target = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joints);
            serializer.Write(this.target);
        }

        public override string ToString()
        {
            return "PlanTrajectoryRequest: " +
            "\njoints: " + joints.ToString() +
            "\ntarget: " + target.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
