//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.GopherMoveItConfig
{
    [Serializable]
    public class PlanTrajectoryResponse : Message
    {
        public const string k_RosMessageName = "gopher_move_it_config/PlanTrajectory";
        public override string RosMessageName => k_RosMessageName;

        public Moveit.RobotTrajectoryMsg trajectory;

        public PlanTrajectoryResponse()
        {
            this.trajectory = new Moveit.RobotTrajectoryMsg();
        }

        public PlanTrajectoryResponse(Moveit.RobotTrajectoryMsg trajectory)
        {
            this.trajectory = trajectory;
        }

        public static PlanTrajectoryResponse Deserialize(MessageDeserializer deserializer) => new PlanTrajectoryResponse(deserializer);

        private PlanTrajectoryResponse(MessageDeserializer deserializer)
        {
            this.trajectory = Moveit.RobotTrajectoryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trajectory);
        }

        public override string ToString()
        {
            return "PlanTrajectoryResponse: " +
            "\ntrajectory: " + trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
