//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.GopherRosClearcore
{
    [Serializable]
    public class HomingResponse : Message
    {
        public const string k_RosMessageName = "gopher_ros_clearcore/Homing";
        public override string RosMessageName => k_RosMessageName;

        public bool state;

        public HomingResponse()
        {
            this.state = false;
        }

        public HomingResponse(bool state)
        {
            this.state = state;
        }

        public static HomingResponse Deserialize(MessageDeserializer deserializer) => new HomingResponse(deserializer);

        private HomingResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "HomingResponse: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
